FROM debian:trixie-slim

RUN apt-get update && apt-get install -y libssl3 ca-certificates && rm -rf /var/lib/apt/lists/*

WORKDIR /app
COPY target/release/pgdam-processor /app/pgdam-processor

RUN chmod +x /app/pgdam-processor

ENTRYPOINT ["/app/pgdam-processor"]
