apiVersion: v1
kind: ConfigMap
metadata:
  name: pgdam-config
  namespace: pgdam
data:
  config.yaml: |
    # pgdam-processor configuration
    # Credentials are resolved from env vars at runtime (see DaemonSet env section)

    kill_mode: auto  # disabled | manual | auto

    sinks:
      elasticsearch:
        enabled: true
        instances:
          - name: elastic-prod
            enabled: true
            url: http://elasticsearch.pgdam.svc.cluster.local:9200
            credentials:
              username_env: ELASTIC_USER
              password_env: ELASTIC_PASS

      kafka:
        enabled: true
        instances:
          - name: prod
            enabled: true
            brokers:
              - http://kafka-sasl.pgdam.svc.cluster.local:9092
            auth:
              mechanism: sasl_plain
              username_env: KAFKA_PROD_USER
              password_env: KAFKA_PROD_PASS
            topics:
              user_query:
                - pgdam.user-queries
              background_worker:
                - pgdam.bg-workers

          - name: nonprod
            enabled: true
            brokers:
              - http://kafka.pgdam.svc.cluster.local:9092
            auth:
              mechanism: none
            topics:
              user_query:
                - pgdam.user-queries
              background_worker:
                - pgdam.bg-workers
